// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnePieceNeu.Models;

#nullable disable

namespace OnePieceNeu.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20260608234116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("OnePieceNeu.Models.Frage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntwortA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AntwortB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AntwortC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AntwortD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fragentext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KorrekteAntwort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Schwierigkeitsgrad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fragen");
                });
#pragma warning restore 612, 618
        }
    }
}
